# Generated by Django 2.2.13 on 2020-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=128)),
                ('password', models.TextField(max_length=128)),
                ('name', models.TextField(max_length=128)),
                ('surname', models.TextField(max_length=128)),
                ('date_of_birth', models.DateTimeField(max_length=10)),
                ('phone', models.TextField(max_length=128)),
            ],
        ),
    ]
