# Generated by Django 2.2.13 on 2020-07-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smate', '0003_auto_20200720_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='explevel',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
