# Generated by Django 2.2.13 on 2020-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smate', '0005_auto_20200723_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to='smate.User'),
        ),
    ]
